version: '3.5'
services:
  gogen:
    build:
      context: gogen
  cribl:
    build:
      context: cribl
    ports:
      - "10080:10080"
      - "10001:10001"
      - "9000:9000"
    volumes:
      - "./cribl/cribl:/opt/cribl/local/cribl"
  apiserver:
    build:
      context: apiserver
    volumes:
      - "./data:/opt/data"
  redis:
    build:
      context: redis
    volumes:
      - "./data:/data"